# Generated by Django 4.2.7 on 2024-02-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_group_table_alter_lesson_table'),
        ('products', '0006_alter_product_table_alter_purchase_table'),
        ('users', '0003_alter_author_table_alter_username_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Username',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
