# Generated by Django 4.2.7 on 2024-02-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Учебные группы',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Уроки',
        ),
    ]
