# Generated by Django 4.2.7 on 2024-02-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_group_table_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
    ]
