# Generated by Django 4.2.7 on 2024-02-29 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_group_table_alter_lesson_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
