# Generated by Django 4.2.7 on 2024-03-01 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_group_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
