# Generated by Django 4.2.7 on 2024-02-28 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 15, 13, 37, 10801), verbose_name='Начало'),
        ),
    ]
