# Generated by Django 4.2.7 on 2024-02-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(default=None, verbose_name='Начало'),
        ),
    ]
