# Generated by Django 4.2.7 on 2024-02-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_start_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Продукты',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='Оплаты',
        ),
    ]
