# Generated by Django 4.2.7 on 2024-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_table_alter_purchase_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество видео'),
        ),
    ]
